repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=100]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=100, --ignore=E203,W503]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.40.0
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
        - eslint@8.40.0
        - eslint-plugin-react@7.32.2
        - eslint-config-prettier@8.8.0
        - "@typescript-eslint/eslint-plugin@5.59.5"
        - "@typescript-eslint/parser@5.59.5"
